[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000
bytecode_hash = "none"
odyssey = true
ffi = true

remappings = [
    "webauthn-sol/=lib/webauthn-sol/"
]
additional_compiler_profiles = [{ name = "via_ir", optimizer_runs = 10000, via_ir = true }]

compilation_restrictions = [
  { paths = "src/MinimalDelegationEntry.sol", via_ir = true },
  { paths = "src/MinimalDelegation.sol", via_ir = true }
]

[profile.default.invariant]
fail_on_revert = true
runs = 100
depth = 500

[profile.default.fuzz]
runs = 1000

[profile.ci.fuzz]
runs = 10000
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
